### ISSUE TITLE
formula like "minutes * 60 + seconds" will cause FormulaException

### ISSUE THREAD

**Issue by yotsubar** [Sun-June/solve-calculate#1]
If contains a function name, it will cause this exception.
Words like "**sum**mer" , "**min**utes",  will cause "INVALID_BRACKET_AFTER_FUNCTION".
Words like "exa**min**ee" , "ad**min**",  will cause "VALUE_DOES_NOT_EXIST".

**Comment by Sun-June** [comment]
@yotsubar 

0.8.4 fix this bug

test case: https://github.com/Sun-June/solve-calculate/blob/cf5f82677fccd9f60c13668482a0b6e2f787cbd7/src/test/java/info/sunjune/solve/calculation/calculator/NumberCalculatorTest.java#L111
